name: 'todolist'
description: 'Create and Archive Github Issues from TODO list'
author: 'acti0nit'
inputs:
  token:
    description: 'Github Authentication Token'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'Target Github Repository'
    required: false
    default: ${{ github.repository }}
  content-filepath:
    description: 'file path to todo list'
    required: false
    default: 'TODO.txt'
outputs:
  issue-numbers:
    description: 'number reference of created issues'
runs:
  using: 'node16'
  main: 'dist/index.js'
