name: CD TODO

on:
  push:
    branches:
      - main

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        token: ${{ secrets.PAT }}
