##
# Label incoming pull requests according to configuration in .github/labeler.yml
##
name: CI PR Labeler
on:
  pull_request:

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    # See documentation: https://github.com/actions/labeler
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
