##
# Run unit test and the action itself
##
name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    uses: acti0nit/todolist/.github/workflows/test.yml@main
  dist:
    uses: acti0nit/todolist/.github/workflows/dist.yml@main
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: acti0nit/todolist/.github/workflows/codeql.yml@main
