##
# Run unit test and the action itself
##
name: CI Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    uses: acti0nit/todolist/.github/workflows/test.yml@main
  dist:
    uses: acti0nit/todolist/.github/workflows/dist.yml@main
