##
# Run unit test and the action itself
##
name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
  runs-on: ubuntu-latest
  - uses: ./.github/workflows/checks/test.yml
  dist:
  runs-on: ubuntu-latest
  - uses: ./.github/workflows/checks/dist.yml
  codeql:
  runs-on: ubuntu-latest
  - uses: ./.github/workflows/checks/codeql.yml
