##
# Run unit test and the action itself
##
name: CI Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    uses: acti0nit/todolist/.github/workflows/test.yml@main
    with:
      token: ${{ secrets.PAT }}
  dist:
    uses: acti0nit/todolist/.github/workflows/dist.yml@main
    