##
# Run unit test and the action itself
##
name: Tests
on:
  push:
    branches:
      - dev/local
  workflow_call:
    secrets:
      token:
        description: 'token to check github commits'
        required: true

jobs:
  # unit tests
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - uses: ./
        with:
          token: ${{ secrets.token }}
          dry-run: true
