##
# Run unit test and the action itself
##
name: Tests
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  # lint tests
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run lint
  # unit tests
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - uses: ./
      with:
        token: ${{ secrets.token }}
        dry-run: true
